/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Archive extends javax.swing.JFrame {

   
    private DoctorDashboard doctorDashboard;
    private AdminDashboard adminDashboard;
    private AccountingDashboard accountingDashboard;
   
    public Archive(DoctorDashboard doctorDashboard) {
        this.doctorDashboard = doctorDashboard;
        initComponents();
    }
    
    public Archive(AccountingDashboard accountingDashboard) {
        this.accountingDashboard = accountingDashboard;
        initComponents();
    }
    // Constructor for Admins
    public Archive(AdminDashboard adminDashboard) {
        this.adminDashboard = adminDashboard;
        initComponents();
    }
    
    public Archive() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        action_label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pati_firstName17 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pati_lastName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pati_age = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pati_birthday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pati_contact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pati_allergies = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pati_address = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pati_ailment = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pati_type = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pati_bloodType = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pati_chronicConditions = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pati_personEmergency = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        pati_contactEmergency = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        pati_physician = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        pati_roomNum = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        pati_admissionDate = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        pati_admissionTime = new javax.swing.JTextField();
        date_combo = new javax.swing.JComboBox<>();
        date_search = new javax.swing.JButton();
        patientID_search = new javax.swing.JTextField();
        searchPatientID = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        back_patientreg1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(948, 723));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 87, 115));

        action_label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        action_label.setForeground(new java.awt.Color(255, 255, 255));
        action_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        action_label.setText("Action");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(action_label, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(action_label, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 200, 70));

        jLabel12.setForeground(new java.awt.Color(24, 87, 115));
        jLabel12.setText("First Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 100, -1));

        pati_firstName17.setBackground(new java.awt.Color(191, 229, 246));
        pati_firstName17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_firstName17.setForeground(new java.awt.Color(24, 87, 115));
        pati_firstName17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_firstName17.setBorder(null);
        pati_firstName17.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_firstName17.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_firstName17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_firstName17ActionPerformed(evt);
            }
        });
        getContentPane().add(pati_firstName17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 130, 30));

        jLabel9.setForeground(new java.awt.Color(24, 87, 115));
        jLabel9.setText("Last Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 60, -1));

        pati_lastName.setBackground(new java.awt.Color(191, 229, 246));
        pati_lastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_lastName.setForeground(new java.awt.Color(24, 87, 115));
        pati_lastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_lastName.setToolTipText("");
        pati_lastName.setBorder(null);
        pati_lastName.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_lastName.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_lastNameActionPerformed(evt);
            }
        });
        getContentPane().add(pati_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 130, 30));

        jLabel10.setForeground(new java.awt.Color(24, 87, 115));
        jLabel10.setText("Age");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 60, -1));

        pati_age.setBackground(new java.awt.Color(191, 229, 246));
        pati_age.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_age.setForeground(new java.awt.Color(24, 87, 115));
        pati_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_age.setBorder(null);
        pati_age.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_age.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_ageActionPerformed(evt);
            }
        });
        getContentPane().add(pati_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 60, 30));

        jLabel11.setForeground(new java.awt.Color(24, 87, 115));
        jLabel11.setText("Birthday");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 60, -1));

        pati_birthday.setBackground(new java.awt.Color(191, 229, 246));
        pati_birthday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_birthday.setForeground(new java.awt.Color(24, 87, 115));
        pati_birthday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_birthday.setBorder(null);
        pati_birthday.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_birthday.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_birthdayActionPerformed(evt);
            }
        });
        getContentPane().add(pati_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 80, 30));

        jLabel6.setForeground(new java.awt.Color(24, 87, 115));
        jLabel6.setText("Contact");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 60, -1));

        pati_contact.setBackground(new java.awt.Color(191, 229, 246));
        pati_contact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_contact.setForeground(new java.awt.Color(24, 87, 115));
        pati_contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_contact.setBorder(null);
        pati_contact.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_contact.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_contactActionPerformed(evt);
            }
        });
        getContentPane().add(pati_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 170, 30));

        jLabel8.setForeground(new java.awt.Color(24, 87, 115));
        jLabel8.setText("Allergies");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 70, -1));

        pati_allergies.setBackground(new java.awt.Color(191, 229, 246));
        pati_allergies.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_allergies.setForeground(new java.awt.Color(24, 87, 115));
        pati_allergies.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_allergies.setBorder(null);
        pati_allergies.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_allergies.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_allergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_allergiesActionPerformed(evt);
            }
        });
        getContentPane().add(pati_allergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 170, 30));

        jLabel13.setForeground(new java.awt.Color(24, 87, 115));
        jLabel13.setText("Address");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 60, -1));

        pati_address.setBackground(new java.awt.Color(191, 229, 246));
        pati_address.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_address.setForeground(new java.awt.Color(24, 87, 115));
        pati_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_address.setBorder(null);
        pati_address.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_address.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_addressActionPerformed(evt);
            }
        });
        getContentPane().add(pati_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 270, 30));

        jLabel14.setForeground(new java.awt.Color(24, 87, 115));
        jLabel14.setText("Ailment");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 60, -1));

        pati_ailment.setBackground(new java.awt.Color(191, 229, 246));
        pati_ailment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_ailment.setForeground(new java.awt.Color(24, 87, 115));
        pati_ailment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_ailment.setBorder(null);
        pati_ailment.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_ailment.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_ailment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_ailmentActionPerformed(evt);
            }
        });
        getContentPane().add(pati_ailment, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 100, 30));

        jLabel15.setForeground(new java.awt.Color(24, 87, 115));
        jLabel15.setText("Type");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 60, -1));

        pati_type.setBackground(new java.awt.Color(191, 229, 246));
        pati_type.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_type.setForeground(new java.awt.Color(24, 87, 115));
        pati_type.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_type.setBorder(null);
        pati_type.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_type.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_typeActionPerformed(evt);
            }
        });
        getContentPane().add(pati_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 100, 30));

        jLabel18.setForeground(new java.awt.Color(24, 87, 115));
        jLabel18.setText("Blood Type");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 130, -1));

        pati_bloodType.setBackground(new java.awt.Color(191, 229, 246));
        pati_bloodType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_bloodType.setForeground(new java.awt.Color(24, 87, 115));
        pati_bloodType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_bloodType.setBorder(null);
        pati_bloodType.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_bloodType.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_bloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_bloodTypeActionPerformed(evt);
            }
        });
        getContentPane().add(pati_bloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 110, 30));

        jLabel19.setForeground(new java.awt.Color(24, 87, 115));
        jLabel19.setText("Chronic Conditions");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 130, -1));

        pati_chronicConditions.setBackground(new java.awt.Color(191, 229, 246));
        pati_chronicConditions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_chronicConditions.setForeground(new java.awt.Color(24, 87, 115));
        pati_chronicConditions.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_chronicConditions.setBorder(null);
        pati_chronicConditions.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_chronicConditions.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_chronicConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_chronicConditionsActionPerformed(evt);
            }
        });
        getContentPane().add(pati_chronicConditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 170, 30));

        jLabel16.setForeground(new java.awt.Color(24, 87, 115));
        jLabel16.setText("Person for Emergency");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 130, -1));

        pati_personEmergency.setBackground(new java.awt.Color(191, 229, 246));
        pati_personEmergency.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_personEmergency.setForeground(new java.awt.Color(24, 87, 115));
        pati_personEmergency.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_personEmergency.setBorder(null);
        pati_personEmergency.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_personEmergency.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_personEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_personEmergencyActionPerformed(evt);
            }
        });
        getContentPane().add(pati_personEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 150, 30));

        jLabel17.setForeground(new java.awt.Color(24, 87, 115));
        jLabel17.setText("Contact for Emergency");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 130, -1));

        pati_contactEmergency.setBackground(new java.awt.Color(191, 229, 246));
        pati_contactEmergency.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_contactEmergency.setForeground(new java.awt.Color(24, 87, 115));
        pati_contactEmergency.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_contactEmergency.setBorder(null);
        pati_contactEmergency.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_contactEmergency.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_contactEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_contactEmergencyActionPerformed(evt);
            }
        });
        getContentPane().add(pati_contactEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 140, 30));

        jLabel20.setForeground(new java.awt.Color(24, 87, 115));
        jLabel20.setText("Physician");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 130, -1));

        pati_physician.setBackground(new java.awt.Color(191, 229, 246));
        pati_physician.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_physician.setForeground(new java.awt.Color(24, 87, 115));
        pati_physician.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_physician.setBorder(null);
        pati_physician.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_physician.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_physician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_physicianActionPerformed(evt);
            }
        });
        getContentPane().add(pati_physician, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 170, 30));

        jLabel21.setForeground(new java.awt.Color(24, 87, 115));
        jLabel21.setText("IP Room Num");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 80, -1));

        pati_roomNum.setBackground(new java.awt.Color(191, 229, 246));
        pati_roomNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_roomNum.setForeground(new java.awt.Color(24, 87, 115));
        pati_roomNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_roomNum.setBorder(null);
        pati_roomNum.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_roomNum.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_roomNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_roomNumActionPerformed(evt);
            }
        });
        getContentPane().add(pati_roomNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 80, 30));

        jLabel22.setForeground(new java.awt.Color(24, 87, 115));
        jLabel22.setText("IP Admission Date");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 100, -1));

        pati_admissionDate.setBackground(new java.awt.Color(191, 229, 246));
        pati_admissionDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_admissionDate.setForeground(new java.awt.Color(24, 87, 115));
        pati_admissionDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_admissionDate.setBorder(null);
        pati_admissionDate.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_admissionDate.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_admissionDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_admissionDateActionPerformed(evt);
            }
        });
        getContentPane().add(pati_admissionDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 100, 30));

        jLabel23.setForeground(new java.awt.Color(24, 87, 115));
        jLabel23.setText("IP Admission Time");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, 100, -1));

        pati_admissionTime.setBackground(new java.awt.Color(191, 229, 246));
        pati_admissionTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pati_admissionTime.setForeground(new java.awt.Color(24, 87, 115));
        pati_admissionTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pati_admissionTime.setBorder(null);
        pati_admissionTime.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        pati_admissionTime.setMargin(new java.awt.Insets(4, 6, 4, 6));
        pati_admissionTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pati_admissionTimeActionPerformed(evt);
            }
        });
        getContentPane().add(pati_admissionTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, 100, 30));

        date_combo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 142, 156)));
        date_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_comboActionPerformed(evt);
            }
        });
        getContentPane().add(date_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 190, 30));

        date_search.setBackground(new java.awt.Color(24, 87, 115));
        date_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date_search.setForeground(new java.awt.Color(255, 255, 255));
        date_search.setText("Search");
        date_search.setBorder(null);
        date_search.setPreferredSize(new java.awt.Dimension(43, 16));
        date_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_searchActionPerformed(evt);
            }
        });
        getContentPane().add(date_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 70, 30));

        patientID_search.setForeground(new java.awt.Color(102, 102, 102));
        patientID_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 142, 156)));
        patientID_search.setDisabledTextColor(new java.awt.Color(126, 142, 156));
        patientID_search.setMargin(new java.awt.Insets(4, 6, 4, 6));
        patientID_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientID_searchActionPerformed(evt);
            }
        });
        getContentPane().add(patientID_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, 30));

        searchPatientID.setBackground(new java.awt.Color(24, 87, 115));
        searchPatientID.setForeground(new java.awt.Color(255, 255, 255));
        searchPatientID.setText("Search");
        searchPatientID.setBorder(null);
        searchPatientID.setPreferredSize(new java.awt.Dimension(43, 16));
        searchPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPatientIDActionPerformed(evt);
            }
        });
        getContentPane().add(searchPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 60, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(24, 87, 115));
        jLabel5.setText("Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 40, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(24, 87, 115));
        jLabel7.setText("Archive");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, -1));

        jPanel2.setBackground(new java.awt.Color(24, 87, 115));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 620));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(24, 87, 115));
        jLabel25.setText("Patient ID:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 90, 30));

        back_patientreg1.setBackground(new java.awt.Color(204, 204, 204));
        back_patientreg1.setText("Back");
        back_patientreg1.setBorder(null);
        back_patientreg1.setPreferredSize(new java.awt.Dimension(43, 16));
        back_patientreg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_patientreg1ActionPerformed(evt);
            }
        });
        getContentPane().add(back_patientreg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 50, 30));

        jLabel1.setBackground(new java.awt.Color(191, 229, 246));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdminBG (948 x 836 px) (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -200, 970, 1020));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pati_firstName17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_firstName17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_firstName17ActionPerformed

    private void pati_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_lastNameActionPerformed

    private void pati_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_ageActionPerformed

    private void pati_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_birthdayActionPerformed

    private void pati_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_contactActionPerformed

    private void pati_allergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_allergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_allergiesActionPerformed

    private void pati_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_addressActionPerformed

    private void pati_ailmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_ailmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_ailmentActionPerformed

    private void pati_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_typeActionPerformed

    private void pati_bloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_bloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_bloodTypeActionPerformed

    private void pati_chronicConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_chronicConditionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_chronicConditionsActionPerformed

    private void pati_personEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_personEmergencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_personEmergencyActionPerformed

    private void pati_contactEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_contactEmergencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_contactEmergencyActionPerformed

    private void pati_physicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_physicianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_physicianActionPerformed

    private void pati_roomNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_roomNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_roomNumActionPerformed

    private void pati_admissionDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_admissionDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_admissionDateActionPerformed

    private void pati_admissionTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pati_admissionTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pati_admissionTimeActionPerformed

    private void date_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_comboActionPerformed

    }//GEN-LAST:event_date_comboActionPerformed

    private void date_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_searchActionPerformed
        
       String selected = date_combo.getSelectedItem().toString(); // Assumes format matches the database's DATETIME format

    String SUrl = "jdbc:mysql://localhost:3306/hospitalsystem";
    String SUser = "root";
    String SPass = "";

    String sql = "SELECT * FROM patientarchive WHERE date_of_action = ?";

    try (Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
         PreparedStatement pst = con.prepareStatement(sql)) {

        // Set the parameter for the query
        pst.setString(1, selected);

        try (ResultSet rs = pst.executeQuery()) {
            while (rs.next()) {
                // Retrieve data from result set
                String name = rs.getString("patient_firstName");
                String lastname = rs.getString("patient_lastName");
                String age = rs.getString("patient_age");
                String bday = rs.getString("patient_birthday");
                String contact = rs.getString("patient_contact");
                String allergies = rs.getString("patient_allergies");
                String address = rs.getString("patient_address");
                String ailment = rs.getString("patient_ailment");
                String type = rs.getString("patient_type");
                String bloodtype = rs.getString("blood_type");
                String chronic = rs.getString("chronic_conditions");
                String person_emergency = rs.getString("person_emergency");
                String contact_emergency = rs.getString("contact_emergency");
                String physician = rs.getString("physician");
                String room_number = rs.getString("room_number");
                String admission_date = rs.getString("admission_date");
                String admission_time = rs.getString("admission_time");
                String action = rs.getString("action");

                // Update GUI components
                pati_firstName17.setText(name);
                pati_lastName.setText(lastname);
                pati_age.setText(age);
                pati_birthday.setText(bday);
                pati_contact.setText(contact);
                pati_allergies.setText(allergies);
                pati_address.setText(address);
                pati_ailment.setText(ailment);
                pati_type.setText(type);
                pati_bloodType.setText(bloodtype);
                pati_chronicConditions.setText(chronic);
                pati_personEmergency.setText(person_emergency);
                pati_contactEmergency.setText(contact_emergency);
                pati_physician.setText(physician);
                pati_roomNum.setText(room_number);
                pati_admissionDate.setText(admission_date);
                pati_admissionTime.setText(admission_time);
                action_label.setText(action);
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
       
    }//GEN-LAST:event_date_searchActionPerformed

    private void patientID_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientID_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientID_searchActionPerformed

    private void searchPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPatientIDActionPerformed
        
        String id = patientID_search.getText();
        
        String SUrl = "jdbc:mysql://localhost:3306/hospitalsystem";
        String SUser = "root";
        String SPass = "";
        
        try {
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            String sql = "SELECT date_of_action from patientarchive where patient_id = " + id + "";

            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                String dates = rs.getString("date_of_action");
                date_combo.addItem(dates);
            }

        } catch (Exception e) {

        }

    }//GEN-LAST:event_searchPatientIDActionPerformed

    private void back_patientreg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_patientreg1ActionPerformed
        this.setVisible(false);

        if (doctorDashboard != null) {
            doctorDashboard.setVisible(true);
        } else if (adminDashboard != null) {
            adminDashboard.setVisible(true);
        }
    }//GEN-LAST:event_back_patientreg1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Archive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Archive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Archive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Archive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Archive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action_label;
    private javax.swing.JButton back_patientreg1;
    private javax.swing.JComboBox<String> date_combo;
    private javax.swing.JButton date_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pati_address;
    private javax.swing.JTextField pati_admissionDate;
    private javax.swing.JTextField pati_admissionTime;
    private javax.swing.JTextField pati_age;
    private javax.swing.JTextField pati_ailment;
    private javax.swing.JTextField pati_allergies;
    private javax.swing.JTextField pati_birthday;
    private javax.swing.JTextField pati_bloodType;
    private javax.swing.JTextField pati_chronicConditions;
    private javax.swing.JTextField pati_contact;
    private javax.swing.JTextField pati_contactEmergency;
    private javax.swing.JTextField pati_firstName17;
    private javax.swing.JTextField pati_lastName;
    private javax.swing.JTextField pati_personEmergency;
    private javax.swing.JTextField pati_physician;
    private javax.swing.JTextField pati_roomNum;
    private javax.swing.JTextField pati_type;
    private javax.swing.JTextField patientID_search;
    private javax.swing.JButton searchPatientID;
    // End of variables declaration//GEN-END:variables
}
